### ISSUE TITLE
NOT FIT first image of the page

### ISSUE THREAD

**Issue by noonosh** [jakhongirnagmatov/TaskVp-wiut#1]
**Please,** review this

`width: 100%` maybe would solve the issue

**Comment by noonosh** [comment]
Any thoughts on that?

**Comment by jakhongirn** [comment]
background-size: cover; property somehow helps to solve our problems. You can check out the site now!

**Comment by noonosh** [comment]
Okay, enable GitHub Pages to see the result.

**Comment by jakhongirn** [comment]
Here it is. But I don't recommend to open via phone. Fine ingredients and footer parts aren't responsive
